<a href="https://colab.research.google.com/github/arman-hossain45/Deep_learning_Neural_network/blob/main/ANN_Dataset_Data_Loader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [11]:
len(df.columns)

31

In [12]:
X_train

array([[-1.81959614,  1.39783991, -1.78945818, ..., -0.97919477,
        -0.19332948,  1.27654123],
       [-1.52580215, -0.58349325, -1.50652239, ..., -1.73047798,
        -0.7277081 ,  0.25879517],
       [ 1.47861459,  0.95088801,  1.50778491, ...,  0.61953591,
         0.00803057, -0.45050863],
       ...,
       [ 1.95465662,  1.65817788,  2.0630413 , ...,  2.63147236,
         1.83266247,  2.51257823],
       [-1.23820516,  2.03370963, -1.24481699, ..., -0.99932916,
        -0.91977461, -0.67900538],
       [ 0.09837438, -1.95429933,  0.08616524, ...,  0.10415563,
        -0.03998606, -0.22824877]])

In [13]:
y_train

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0])

In [14]:
X_train

array([[-1.81959614,  1.39783991, -1.78945818, ..., -0.97919477,
        -0.19332948,  1.27654123],
       [-1.52580215, -0.58349325, -1.50652239, ..., -1.73047798,
        -0.7277081 ,  0.25879517],
       [ 1.47861459,  0.95088801,  1.50778491, ...,  0.61953591,
         0.00803057, -0.45050863],
       ...,
       [ 1.95465662,  1.65817788,  2.0630413 , ...,  2.63147236,
         1.83266247,  2.51257823],
       [-1.23820516,  2.03370963, -1.24481699, ..., -0.99932916,
        -0.91977461, -0.67900538],
       [ 0.09837438, -1.95429933,  0.08616524, ...,  0.10415563,
        -0.03998606, -0.22824877]])

In [15]:
type(y_train)

numpy.ndarray

In [16]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [17]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_1720/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_1720/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_1720/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_1720/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [18]:
type(X_train_tensor)

torch.Tensor

#Data set and data loader

In [42]:
from torch.utils.data import Dataset, DataLoader

In [45]:
class CustomDataset(Dataset):
  def __init__(self, X, y):
    self.features = X
    self.labels = y

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [46]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [47]:
len(train_dataset)

455

# now we need the dataloder

In [48]:
train_loader =DataLoader(train_dataset, batch_size =32,shuffle=True)
test_loader =DataLoader(test_dataset, batch_size =32,shuffle=True)

# Defining the Model

In [19]:
X_train.shape[1]

30

In [20]:
import torch.nn as nn

In [21]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [22]:
torch.rand(30,1)

tensor([[0.5363],
        [0.9796],
        [0.8230],
        [0.8349],
        [0.4454],
        [0.1350],
        [0.1872],
        [0.2729],
        [0.7635],
        [0.3589],
        [0.5274],
        [0.7691],
        [0.2109],
        [0.2498],
        [0.4569],
        [0.0940],
        [0.9900],
        [0.4121],
        [0.4872],
        [0.8517],
        [0.2970],
        [0.4320],
        [0.0815],
        [0.0665],
        [0.8684],
        [0.6686],
        [0.0429],
        [0.0709],
        [0.4790],
        [0.6799]])

# Parameters

In [23]:
X_train_tensor.shape[1]

30

In [24]:
learning_rate = 0.1
epochs = 25

In [25]:
loss_function = nn.BCELoss()

In [26]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [27]:
model = MySimpleNN(X_train_tensor.shape[1])

In [28]:
model.parameters()

In [29]:
X_test_tensor.dtype

torch.float32

In [30]:
model.linear.weight.dtype

torch.float32

In [31]:
y_train_tensor.dtype

torch.float32

In [32]:
model.parameters()

# Training Pipeline

In [49]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    #forward pass

    y_pred = model.forward(batch_features)

    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

   #zero gradient
    optimizer.zero_grad()


  #backward pass
    loss.backward()


  #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.09460602700710297
 2 , Loss = 0.429093599319458
 3 , Loss = 0.25425729155540466
 4 , Loss = 0.1963607221841812
 5 , Loss = 0.022277707234025
 6 , Loss = 0.02151140756905079
 7 , Loss = 0.12988020479679108
 8 , Loss = 0.08928696066141129
 9 , Loss = 0.11598231643438339
 10 , Loss = 0.014549740590155125
 11 , Loss = 0.01357304211705923
 12 , Loss = 0.05384395644068718
 13 , Loss = 0.02694271132349968
 14 , Loss = 0.016464686021208763
 15 , Loss = 0.0178879015147686
 16 , Loss = 0.02027895860373974
 17 , Loss = 0.006818145979195833
 18 , Loss = 0.008833022788167
 19 , Loss = 0.019809752702713013
 20 , Loss = 0.06394068896770477
 21 , Loss = 0.003143521025776863
 22 , Loss = 0.1293140947818756
 23 , Loss = 0.011119126342236996
 24 , Loss = 0.11792642623186111
 25 , Loss = 0.012537391856312752

# Trainning pipe line version 2

In [34]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
Batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)
#mini batch gradientsn descent
for epoch in range(epochs):

  for start_indx in range(0,n_sample,Batch_size):
    end_indx =start_indx+Batch_size

    print(f" start index {start_indx}, end Index {end_indx}")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]



    #forward pass

    y_pred = model(X_batch)


    #Loss calculate
    loss = loss_function(y_pred,y_batch.reshape(-1,1))

    #upgrate  step
    optimizer.zero_grad()

    #backward pass
    loss.backward()


    #parameter update
    optimizer.step()

    #





  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 1 , Loss = 0.2550426721572876
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 2 , Loss = 0.1541716754436493
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 3 , Loss = 0.1105986088514328
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 4 , Loss = 0.08637130260467529
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 5 , Loss = 0.07086731493473053
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 6 , Loss = 0.060077399015426636
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 7 , Loss = 0.052138350903987885
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 8 , Loss = 0.04605839401483536
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 9 , Loss = 0.041258662939071655
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 10 , Loss = 0.0373777374625206
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 11 , Loss = 0.03417814150452614
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 12 , Loss = 0.03149743750691414
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 13 , Loss = 0.02922075428068638
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 14 , Loss = 0.02726452238857746
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 15 , Loss = 0.025566667318344116
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 16 , Loss = 0.02408001758158207
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 17 , Loss = 0.022768184542655945
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 18 , Loss = 0.021602584049105644
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 19 , Loss = 0.02056049183011055
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 20 , Loss = 0.019623639062047005
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 21 , Loss = 0.018777145072817802
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 22 , Loss = 0.018008841201663017
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 23 , Loss = 0.017308542504906654
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 24 , Loss = 0.016667824238538742
 start index 0, end Index 32
 start index 32, end Index 64
 start index 64, end Index 96
 start index 96, end Index 128
 start index 128, end Index 160
 start index 160, end Index 192
 start index 192, end Index 224
 start index 224, end Index 256
 start index 256, end Index 288
 start index 288, end Index 320
 start index 320, end Index 352
 start index 352, end Index 384
 start index 384, end Index 416
 start index 416, end Index 448
 start index 448, end Index 480
 25 , Loss = 0.016079502180218697

# Model Evaluation

In [35]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5730994343757629

# better version

In [53]:
model.eval()# evaluation mode
accuracy_list =[]

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred= (y_pred > 0.5).float()
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f" Accuracy = {overall_accuracy}")

 Accuracy = 0.9861111044883728

In [54]:
accuracy_list

[1.0, 1.0, 1.0, 0.9444444179534912]

# Summary

In [36]:
X_train_tensor.shape

torch.Size([455, 30])

In [37]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [38]:
from torchinfo import summary

In [39]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================