<a href="https://colab.research.google.com/github/arman-hossain45/Deep_learning_Neural_network/blob/main/Pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [ ]:
df.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [18]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [19]:
df.shape

(569, 33)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [22]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head(4)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300

In [23]:


x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# scaling

In [24]:
scaler= StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [25]:
x_train

array([[ 0.0460138 ,  1.30110482,  0.10477803, ...,  0.06592268,
         0.49798621,  1.07396589],
       [-1.55596899, -1.12145256, -1.55154481, ..., -1.77099761,
        -0.49463134, -0.27808002],
       [ 1.34715864,  0.72649443,  1.37293147, ...,  0.83270352,
         0.5079958 ,  0.50124787],
       ...,
       [ 1.10681978,  0.2874921 ,  1.10481446, ...,  0.53086931,
         0.30947229, -0.26956588],
       [-0.31311323, -0.2549401 , -0.35662333, ..., -0.17798375,
        -1.09020188, -0.80198362],
       [-0.13907475, -0.8134614 , -0.11051592, ...,  0.33726858,
        -0.49963614,  1.11369856]])

In [26]:
y_train

541    B
175    B
198    M
547    B
332    B
      ..
121    M
560    B
516    M
464    B
73     M
Name: diagnosis, Length: 455, dtype: object

# label encoder for target vaariable

In [27]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)

In [28]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1])

# numpy array to pytorch tensors

In [46]:
x_train_tensor= torch.from_numpy(x_train)
x_test_tensor= torch.from_numpy(x_test)
x_train_tensor= torch.tensor(x_train,dtype=torch.float32)
x_test_tensor= torch.tensor(x_test,dtype=torch.float32)
y_train_tensor= torch.from_numpy(y_train)
y_test_tensor= torch.from_numpy(y_test)
y_train_tensor= torch.tensor(y_train,dtype=torch.float32)
y_test_tensor= torch.tensor(y_test,dtype=torch.float32)

In [30]:
x_test_tensor.shape

torch.Size([114, 30])

In [31]:
y_train_tensor.shape

torch.Size([455])

# Define the model

In [39]:
import torch.nn as nn

In [40]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

# Important parameters

In [41]:
learning_rate = 0.1
epochs= 25

In [42]:
loss_function = nn.BCELoss()

In [43]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [49]:
model.parameters()

# Trainning pipe line

In [51]:
# create model
model = MySimpleNN(x_train_tensor.shape[1])

#opitimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(x_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.reshape(-1, 1))

    # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()



  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7929204702377319
Epoch: 2, Loss: 0.5713481903076172
Epoch: 3, Loss: 0.460223913192749
Epoch: 4, Loss: 0.39563995599746704
Epoch: 5, Loss: 0.35304346680641174
Epoch: 6, Loss: 0.32252612709999084
Epoch: 7, Loss: 0.29938003420829773
Epoch: 8, Loss: 0.28108251094818115
Epoch: 9, Loss: 0.2661588191986084
Epoch: 10, Loss: 0.2536877393722534
Epoch: 11, Loss: 0.2430630475282669
Epoch: 12, Loss: 0.23386867344379425
Epoch: 13, Loss: 0.22580881416797638
Epoch: 14, Loss: 0.21866700053215027
Epoch: 15, Loss: 0.21228072047233582
Epoch: 16, Loss: 0.20652543008327484
Epoch: 17, Loss: 0.20130373537540436
Epoch: 18, Loss: 0.19653832912445068
Epoch: 19, Loss: 0.19216683506965637
Epoch: 20, Loss: 0.18813827633857727
Epoch: 21, Loss: 0.18441064655780792
Epoch: 22, Loss: 0.18094871938228607
Epoch: 23, Loss: 0.1777229756116867
Epoch: 24, Loss: 0.17470815777778625
Epoch: 25, Loss: 0.1718827486038208

In [ ]:
model.weights

In [ ]:
model.bias

# Evaluation

In [52]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5443213582038879

In [53]:
#summary

from torchinfo import summary
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================

# Here we can see that our original prediction is  0 or 1 so we decide to set up a threshold so that it can be predict if less then 0.5 then it will be 0 and greater than 0.5 it will be 1 so we set a threshold value

In [ ]:
print("hellow world")

# in this module we do this use pytorch library module

1.Building a neural network using NN module

2.Using built-in activation function

3.Using built-in  loss function

4.Using built-in Optimizer


So what is the NN model in torch

wide array of classes and functions designed to help the developers build  neural network s efficiency and effectively


key components of torch of NN

1.Modeles (layers )

2.Activation function

3.Loss function

4.Container Modules

5.Regularization and dropout

# Here in only a One neuron

In [ ]:
import torch
import torch.nn as nn  # base class sob module ase aikhan neural network ar

class Model(nn.Module):  #  aikhan a amra nn class ke inherit kotesi karon ta na hole amra nn class ar sob
#functionality use korte parbo na. nn hol0 akta build in class
    def __init__(self, num_features):
        super().__init__()# we use super keyword child class parent class ar constructor ke call korte pare
        self.linear = nn.Linear(num_features, 1)  # Capital L, single neuron we create
        # Here input is num 0f feature and 1 output
        self.sigmoid = nn.Sigmoid()              # Capital S

    # forward pass
    def forward(self, features):
        out = self.linear(features)  # z = wx + b
        out = self.sigmoid(out)
        return out


# create a dummy dataset
features = torch.rand(10, 5)

# create a model
# object create of this model
model = Model(features.shape[1])

# call model for forward pass
output = model(features)
print(output)

tensor([[0.5304],
        [0.5218],
        [0.5593],
        [0.6020],
        [0.5264],
        [0.5879],
        [0.5329],
        [0.5948],
        [0.6339],
        [0.6216]], grad_fn=<SigmoidBackward0>)

In [ ]:
# see weight

model.linear.weight

Parameter containing:
tensor([[-0.2835,  0.3714,  0.2618,  0.1645, -0.2310]], requires_grad=True)

In [ ]:
# see the bias

model.linear.bias

Parameter containing:
tensor([0.1381], requires_grad=True)

In [ ]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [ ]:
from torchinfo import summary

In [ ]:
summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# Here now we code With hidden layer

5 input and 3 neuron of 1 hidden layer  and 1 output layer

In [ ]:
class Model(nn.Module):  #  aikhan a amra nn class ke inherit kotesi karon ta na hole amra nn class ar sob
#functionality use korte parbo na. nn hol0 akta build in class
    def __init__(self, num_features):
        super().__init__()# we use super keyword child class parent class ar constructor ke call korte pare

        self.linear1 = nn.Linear(num_features, 3)  #here number of feature is 5 and hidden laayer 1 is 3 neuron
        #and one output layer which is connected in one hidden layer which has 3 neuron

        self.relu=nn.ReLU()# we use relu activation function in hidden layer

        self.linear2 = nn.Linear(3, 1)#use sigmoid in output layer

        self.sigmoid = nn.Sigmoid()#use sigmoid in output layer

    # forward pass
    def forward(self, features):
        out = self.linear1(features)  # z = wx + b
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [ ]:
# create model

features = torch.rand(10, 5)
model = Model(features.shape[1])

model(features)

tensor([[0.3968],
        [0.3968],
        [0.3968],
        [0.3968],
        [0.3968],
        [0.3968],
        [0.3968],
        [0.3968],
        [0.3968],
        [0.3968]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.0193, -0.0561, -0.2429, -0.4263,  0.3724],
        [-0.1341, -0.3256, -0.4178, -0.1022,  0.0675],
        [-0.3138,  0.1585,  0.0407, -0.4284, -0.2278]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0855,  0.2254, -0.1443]], requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# Now in this code we do all of this things use a squential container

In [ ]:
class Model(nn.Module):  #  aikhan a amra nn class ke inherit kotesi karon ta na hole amra nn class ar sob
#functionality use korte parbo na. nn hol0 akta build in class
    def __init__(self, num_features):

        super().__init__()# we use super keyword child class parent class ar constructor ke call korte pare
# now we can do all of this using a sequential container
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )




    # forward pass
    def forward(self, features):
        out =self.network(features)


        return out

In [ ]:
# create model

features = torch.rand(10, 5)
model = Model(features.shape[1])

model(features)

tensor([[0.6131],
        [0.5808],
        [0.5519],
        [0.5581],
        [0.5519],
        [0.5629],
        [0.5553],
        [0.5627],
        [0.5607],
        [0.5693]], grad_fn=<SigmoidBackward0>)