<a href="https://colab.research.google.com/github/arman-hossain45/Deep_learning_Neural_network/blob/main/single_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# From Scaratch perceptron

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [23]:
class perceptron:
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights:{self.weights}")
    self.eta =eta
    self.epochs= epochs

  def activationFunction(self,input,weights):
    z=np.dot(input,weights)
    return np.where(z>0,1,0)

  def fit(self,x,y):
    self.x=x
    self.y=y
    x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
    print(f"x with bias{x_with_bias}")

    for epoch in range(self.epochs):
      print(f"Epoch ",epoch)


      y_hat=self.activationFunction(x_with_bias,self.weights)
      print(f"Predicted values{y_hat}")
      error=self.y-y_hat
      print(f"error \n {error}")

      #weights upgrede
      self.weights=self.weights+ self.eta*np.dot(x_with_bias.T,error)
      print(f" Updated weights \n {self.weights}")

  def predict(self,x):
    x_with_bias=np.c_[x,-np.ones((len(x),1))]
    return self.activationFunction(x_with_bias,self.weights)

In [2]:
w=np.array([2,2])
x=np.array([2,2])
dot=np.dot(w,x)
dot

np.int64(8)

# Normal distribution

In [3]:
random=np.random.seed(42)

In [4]:
random_normal=np.random.randn(3)
random_normal

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [6]:
random_nor=np.random.rand(3)
random_nor# without negative value show this 3 values

array([0.86617615, 0.60111501, 0.70807258])

# Concatenation

In [22]:
import pandas as pd
data={
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}
AND=pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [21]:
x=AND.drop('y',axis=1)
y=AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [24]:
model=perceptron(eta=0.5,epochs=10)
model.fit(x,y)

self.weights:[ 1.52302986e-04 -4.69474386e-05  5.42560044e-05]
x with bias[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch  0
Predicted values[0 0 1 1]
error
 0    0
1    0
2   -1
3    0
Name: y, dtype: int64
 Updated weights
 [-4.99847697e-01 -4.69474386e-05  5.00054256e-01]
Epoch  1
Predicted values[0 0 0 0]
error
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.42560044e-05]
Epoch  2
Predicted values[0 1 1 1]
error
 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
 Updated weights
 [-4.99847697e-01 -4.69474386e-05  1.00005426e+00]
Epoch  3
Predicted values[0 0 0 0]
error
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.00054256e-01]
Epoch  4
Predicted values[0 0 0 1]
error
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.00054256e-01]
Epoch  5
Predicted values[0 0 0 1]
error
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.00054256e-01]
Epoch  6
Predicted values[0 0 0 1]
error
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.00054256e-01]
Epoch  7
Predicted values[0 0 0 1]
error
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.00054256e-01]
Epoch  8
Predicted values[0 0 0 1]
error
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.00054256e-01]
Epoch  9
Predicted values[0 0 0 1]
error
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
 Updated weights
 [1.52302986e-04 4.99953053e-01 5.00054256e-01]

In [13]:
a=len(x)

In [16]:
bias=np.c_[x,-np.ones((a,1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [17]:
x

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1